# Generated by Django 3.2.15 on 2022-08-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
