# Generated by Django 3.2.15 on 2022-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='Please enter post here'),
        ),
    ]
