# Generated by Django 3.2.15 on 2022-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0003_remove_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Welcome to codezone', max_length=255),
        ),
    ]
