# Generated by Django 3.2.15 on 2022-08-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0004_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Welcome to code zone', max_length=255),
        ),
    ]
