# Generated by Django 3.2.15 on 2022-08-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0006_auto_20220822_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default='general coding', max_length=255),
        ),
    ]
