# Generated by Django 3.2.15 on 2022-08-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0007_auto_20220823_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
