# Generated by Django 3.2.15 on 2022-08-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0008_rename_catagory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
