# Generated by Django 3.2.15 on 2022-08-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0012_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
