# Generated by Django 3.2.15 on 2022-08-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0014_profile'),
    ]

    operations = [


    ]
